fix issue #26
BoYanZh/Canvas-Syncer pull request #31
Opened 2021-12-08 01:53 UTC by jackye666

Fix #26. 
Requirements satisfied:
If you drop a course , then next time you use this project, it will automatically delete the courseID and courseCode from the config file and inform the user.
Design idea:
If the course is dropped, then you cannnot successfully get the relative cousre information from canvas. 
For courses downloaded through courseID, I check the return json object. If the json object does not contain "id", then it means that we failed to access the course page. I then delete this courseID from the config.
For courses downloaded through courseCode, I create a list which keeps appending successfully downloaded coursesCode. Then, I compare the list with the courseCode in config file , and delete them.
Quality Assurance:
I conduct peer review with my teamate spikedyf and there is no obviou bug found. What's more, I test on the following test: 
I am in course "EECS 477 001 FA 2021" and not in "EECS 496". I enter both course code to the config, and it turns out that "EECS 496" is successfully deleted and the files from "EECS 477 001 FA 2021" are successfully downloaded.

2021-12-08 03:09 UTC, BoYanZh commented
Thanks for your contribution and observation. But I think it may be better to leave the config file unchanged but just prompt users that some course Code/course ID is unreachable, then skip these courses in the following steps. If you want to override the config files, it may break the config file under some special conditions.

2021-12-08 05:32 UTC, jackye666 commented
Thank you for your comments, I changed my code so that it only inform the user and won't change the config.

2021-12-09 00:58 UTC, BoYanZh requested changes

2021-12-09 00:58 UTC, BoYanZh commented on canvassyncer/__main__.py
> +            #print(course)
Commented debug lines should be deleted.

2021-12-09 00:58 UTC, BoYanZh commented on canvassyncer/__main__.py
> +            with open(".canvassyncer.json","r+") as f:
Users may specify the config file through -p.

2021-12-09 00:58 UTC, BoYanZh commented on canvassyncer/__main__.py
> +droppedCourse={"courseIDs":[],"courseCodes":[]}
Consider storing the value inside the class.

2021-12-09 00:58 UTC, BoYanZh commented on canvassyncer/__main__.py
> +            correct_courseCode = []
Unify the naming style with the project. Use camel case.

2021-12-09 00:58 UTC, BoYanZh commented on canvassyncer/__main__.py
> +                    if i not in droppedCourse["courseCodes"]:
Combine consecutive `if` with `and`.

2022-09-16 09:38 UTC, closed without merging