Change the default link and allow retry to handle 403 because of frequent visit
BoYanZh/Canvas-Syncer pull request #35
Opened 2022-08-30 11:57 UTC by wznmickey

1. Change from umjicanvas.com to jicanvas.com.
2. Allow retry in `clientGetJson`. Otherwise, there will be `403 Forbidden (Rate Limit Exceeded)` appearing.
`

2022-08-30 12:05 UTC, wznmickey commented
自动回复：已收到，谢谢。

2022-08-31 15:58 UTC, BoYanZh requested changes

2022-08-31 15:58 UTC, BoYanZh commented on canvassyncer/__main__.py
> +    prevu = oldConfig.get("canvasURL", "") if oldConfig else "https://jicanvas.com"
should have another separated PR

2022-08-31 15:58 UTC, BoYanZh commented on canvassyncer/__main__.py
> +            check=0
need reformat

2022-08-31 15:58 UTC, BoYanZh commented on canvassyncer/__main__.py
> +                resp = await self.client.get(*args, **kwargs)
retryable error may occur here

2022-08-31 15:58 UTC, BoYanZh commented on canvassyncer/__main__.py
> +                    check = 10
just `break`

2022-09-01 07:11 UTC, wznmickey commented on canvassyncer/__main__.py
> +    prevu = oldConfig.get("canvasURL", "") if oldConfig else "https://jicanvas.com"
Open in https://github.com/BoYanZh/Canvas-Syncer/pull/37

2022-09-01 07:36 UTC, wznmickey commented on canvassyncer/__main__.py
> +                    check = 10
directly return now

2022-09-01 08:29 UTC, BoYanZh requested changes

2022-09-01 08:29 UTC, BoYanZh commented on canvassyncer/__main__.py
> +        while (retryTimes <= 5):
`()` can be removed.

2022-09-01 08:29 UTC, BoYanZh commented on canvassyncer/__main__.py
> +            except Exception:
Better catch more detailed exception.

2022-09-01 08:29 UTC, BoYanZh commented on README.md
> +2. `courseID` should be an integer. Check the canvas link of the course. e.g. `courseID = 7` for <https://jicanvas.com/courses/7>.
Need to rebase on #36.

2022-09-08 14:44 UTC, BoYanZh requested changes

2022-09-08 14:44 UTC, BoYanZh commented on canvassyncer/__main__.py
> +        folders = await self.client.json(url,debug=self.config["debug"])
need space after comma

2022-09-08 15:21 UTC, BoYanZh approved these changes

2022-09-08 15:22 UTC, merged