allow remove old config
BoYanZh/Canvas-Syncer pull request #40
Opened 2022-09-09 07:38 UTC by wznmickey

Fix https://github.com/BoYanZh/Canvas-Syncer/issues/24.
When using `-r`, if input `remove`, it will not keep the old config. Instead, it will store the default value.

2022-09-15 06:20 UTC, BoYanZh commented
I think we may need to hint the user to input "remove" somewhere for storing the default value?

2022-09-15 06:34 UTC, wznmickey commented
> I think we may need to hint the user to input "remove" somewhere for storing the default value?

Add hint message.

Like 
```
Maximum file size to download(MB)(Default: 20480.0)(If you input remove, value will change to 250): 
``` 
if there is a default value and 
```
Courses to sync in course ID(split with space)(Default: 1)(If you input remove, value will change to empty): 
``` 
if there is no default value.

2022-09-16 09:36 UTC, BoYanZh requested changes

2022-09-16 09:36 UTC, BoYanZh commented on canvassyncer/__main__.py
> +        tipRemove = "(If you input remove, value will change to " + (f"{defaultValOnRemove})" if defaultValOnRemove != "" else "empty)")
'will be changed to' or 'will become'.

2022-09-17 05:19 UTC, wznmickey commented on canvassyncer/__main__.py
> +        tipRemove = "(If you input remove, value will change to " + (f"{defaultValOnRemove})" if defaultValOnRemove != "" else "empty)")
changed.

2022-09-17 09:04 UTC, merged