feat: allow filter files by type
BoYanZh/Canvas-Syncer pull request #48
Opened 2023-06-01 05:21 UTC by wznmickey

Do https://github.com/BoYanZh/Canvas-Syncer/issues/44

Require mimetypes

2023-06-05 21:03 UTC, BoYanZh requested changes

2023-06-05 21:03 UTC, BoYanZh commented on canvassyncer/__main__.py
> +        if (not isAudio) or (self.config["allowAudio"]):
remove nested `if` and parentheses

2023-06-05 21:03 UTC, BoYanZh commented on canvassyncer/__main__.py
> +        except Exception:
What kind of Exception will appear here?

2023-06-05 21:03 UTC, BoYanZh commented on canvassyncer/__main__.py
> +        print(f"remove {st} because of its file type.")
capitalize the first letter, and print the file type in the message

2023-06-05 21:03 UTC, BoYanZh commented on canvassyncer/__main__.py
> +    def checkAllowDownload(self, st):
What does it mean by `st`?

2023-06-06 05:49 UTC, wznmickey commented on canvassyncer/__main__.py
> +        if (not isAudio) or (self.config["allowAudio"]):
Removed

2023-06-06 05:50 UTC, wznmickey commented on canvassyncer/__main__.py
> +        except Exception:
The [0] may return None, not string. Now check it before using it.

2023-06-06 05:50 UTC, wznmickey commented on canvassyncer/__main__.py
> +        print(f"remove {st} because of its file type.")
Changed.

2023-06-06 05:50 UTC, wznmickey commented on canvassyncer/__main__.py
> +    def checkAllowDownload(self, st):
the filename.

2023-06-30 06:46 UTC, BoYanZh requested changes

2023-06-30 06:46 UTC, BoYanZh commented on canvassyncer/__main__.py
> +__version__ = "2.0.11"
do not change it now

2023-06-30 07:17 UTC, wznmickey commented on canvassyncer/__main__.py
> +__version__ = "2.0.11"
changed back in 6dad3ae

2023-06-30 13:40 UTC, BoYanZh approved these changes

2023-06-30 13:40 UTC, merged