refactor: get online files and local files logic, fix: wrong download size; and more
BoYanZh/Canvas-Syncer pull request #60
Opened 2024-12-27 04:01 UTC by Ruizhi-Deng

**Below changes have been made:**
1. fix asyncio .close() method error, update the code to work for latest packages
2. change the organization of the code. Deleted getCourseTaskInfo(), use separate functions to get online and local files, use better ways to get a download list. 
3. fix wrong download size calculation and missing courses.
4. Improve readability of the code.

**TODO:**
- [ ] Beautify output
- [ ] More tests
- [ ] Packing

2024-12-27 04:02 UTC, wznmickey commented
You don't need to close and open.
All you commits will be updated.

2024-12-27 08:51 UTC, Ruizhi-Deng commented
Strangely, if I add 
```
httpx
tqdm
aiofiles
```
into `requirements.txt,`
I failed to pass the code quality test 
the report says that "Statement seems to have no effect"

I have to remove them to satisfy the code quality test (not good though). No idea why.

2024-12-27 08:56 UTC, Ruizhi-Deng commented
> You don't need to close and open. All your commits will be updated directly.
> 
> By the way, do you have any interest in https://github.com/wznmickey/canvas_syncer that we can handle the area of each network connection issues rather than plenty of try catch.

Glad to help, but I have no experience in rust 🤣

2024-12-27 14:58 UTC, wznmickey commented
> Strangely, if I add
> 
> ```
> httpx
> tqdm
> aiofiles
> ```
> 
> into `requirements.txt,` I failed to pass the code quality test the report says that "Statement seems to have no effect"
> 
> I have to remove them to satisfy the code quality test (not good though). No idea why.

maybe you can try setting the version?

2025-01-04 08:13 UTC, BoYanZh commented
Please edit the original file in this PR so that I can see which lines have changed and merge it. If needed, you can create a new PR to split it into multiple files later.

2025-02-17 09:12 UTC, BoYanZh requested changes

2025-02-17 09:12 UTC, BoYanZh commented on requirements.txt
> +aiofiles
Why are the versions removed?

2025-06-05 12:11 UTC, closed without merging